### ISSUE TITLE
Namespacing functions?

### ISSUE THREAD

**Issue by devnix** [Innmind/BlackBox#9]
Hi! What do you think about namespacing functions like `proof`,  `test`, `property`, etc to avoid polluting the global namespace? It could be done by deprecating the global functions for a new minor version, and then deleting those for the next major version.

I can work on a PR if you are cool with the idea 😄

**Comment by Baptouuuu** [comment]
I wasn't sure which way to go when I created them, I went with globals to avoid importing them for each file.

Instead of deprecating them for now maybe let it that way and add a method on `Application` to tell to use namespaced functions ?

**Comment by Baptouuuu** [comment]
Just to mention that I started working on this.

**Comment by Baptouuuu** [comment]
Released in version `5.2.0`:
- namespaced functions
- `Application::disableGlobalFunctions()` method

**Comment by devnix** [comment]
Huh, that is bizarre behavior if you ask me.

If a function is available according to your IDE, it could lead to confusion about which function you should use, and you may be importing a function that is not included, or not declared (as a consumer of the API I would be very confused).

If you are OK with a future major version offering only the namespaced functions, deprecating the non-namespaced functions would immediately tell the developer which function should use to future-proof his code, and to document which functions should be replaced by others.

**Comment by Baptouuuu** [comment]
You mean not deprecating global functions is bizarre ?

I used global functions in order to avoid `use` statements. 

I don't plan on making a new major version anytime soon as not all Innmind packages use BlackBox 5 yet. Until I have more perspective on what works and what doesn't I prefer not deprecating things.

**Comment by devnix** [comment]
> You mean not deprecating global functions is bizarre?

I mean two things that seem very funky:

- The fact that by calling `Application::disableGlobalFunctions()` some functions will stop working, but there is no way to prevent confusion by using static analysis or IDE autocompletion
- There is no canonical option, so when using autocompletion one will probably start mixing by accident namespace and global functions

> Until I have more perspective on what works and what doesn't I prefer not deprecating things.

Absolutely understandable! There are projects like https://github.com/laravel/laravel that (if I'm not wrong) declares global functions. A lot of people are OK with that, but it also collides with other libraries and userland code. There are other popular projects like https://github.com/azjezz/psl that are highly functional and have all the functions namespace, and is wildly accepted.

If I would want to avoid importing every function, I would `use` the root namespace like this:

```php
use Innmind\BlackBox\Runner;

Runner\proof(...);
Runner\test(...);
Runner\given(...);
Runner\property(...);
Runner\properties(...);
```

instead of 

```php

use function Innmind\BlackBox\Runner\proof;
use function Innmind\BlackBox\Runner\test;
use function Innmind\BlackBox\Runner\given;
use function Innmind\BlackBox\Runner\property;
use function Innmind\BlackBox\Runner\properties;

proof(...);
test(...);
given(...);
property(...);
properties(...);
```

**Comment by Baptouuuu** [comment]
> The fact that by calling `Application::disableGlobalFunctions()` some functions will stop working

Maybe this is a naming problem then, what this method does is prevent the method `tryToProve` to load the PHP file containing the global functions. Until `tryToProve` is called the global functions are not yet loaded.

My rationale behind these functions is to ease the creation of objects the runner expect. If I need to `use` a namespace then I might as well directly reference the classes.

I'll try to find a solution that is both as convenient as global functions, doesn't affect the global namespace and plays nice with IDEs 🤔.
